/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "system_stm32f4xx.h"
#include "eventman.h"
#include "timer.h"
#include "led.h"
#include "melody.h"
#include "lightsensor.h"
#include "temhumsensor.h"
#include "eventbutton.h"
#include "button.h"
#include "Ucglib.h"
#include "uartcmd.h"
#include "serial.h"
#include "stdio.h"
#include "string.h"
#include "stm32f401re_rcc.h"
#include "stm32f401re_gpio.h"
#include "stm32f401re_usart.h"
#include "misc.h"
#include "stm32f401re.h"
#include "buff.h"

#define GPIO_PIN_SET				1
#define GPIO_PIN_RESET				0
#define GPIO_PIN_LOW				0
#define GPIO_PIN_HIGH				1

#define USART2_TX					GPIO_Pin_2  //PA2		 / PD5
#define USART2_RX					GPIO_Pin_3 //PA3         / PD6
#define USART2_GPIO					GPIOA
#define USART2_GPIO_CLOCK			RCC_AHB1Periph_GPIOA
#define USART2_CLOCK				RCC_APB1Periph_USART2

#define USARTx_Buad					9600

void USART2_Init(void);
void Serial_Init(void);
uint8_t PollRxBuff(void);

//Init USART2
void USART2_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStruct;
	USART_InitTypeDef USART_Initstruct;
	NVIC_InitTypeDef NVIC_InitStruct;

	/*
	 * Init TX for USART2
	 */

	//Enable GPIOClock for PA2
	RCC_AHB1PeriphClockCmd(USART2_GPIO_CLOCK, ENABLE);

	//Alternate function mode
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_AF;

	//Clock speed
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;

	//Output type push-pull
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP;

	//Enable pull-up resistor
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;

	//PA2 TX pin
	GPIO_InitStruct.GPIO_Pin = USART2_TX;
	GPIO_Init(USART2_GPIO, &GPIO_InitStruct);

	//Alternate function config
	GPIO_PinAFConfig(USART2_GPIO, GPIO_PinSource2, GPIO_AF_USART2);

	//Enable clock for USART2 peripheral
	RCC_APB1PeriphClockCmd(USART2_CLOCK, ENABLE);

	//Enable USART2 peripheral
	USART_Cmd(USART2, ENABLE);

	//PA3 RX pin
	GPIO_InitStruct.GPIO_Pin = USART2_RX;
	GPIO_Init(USART2_GPIO, &GPIO_InitStruct);


	USART_Initstruct.USART_BaudRate = USARTx_Buad;
	USART_Initstruct.USART_WordLength = USART_WordLength_8b;
	USART_Initstruct.USART_StopBits = USART_StopBits_1;
	USART_Initstruct.USART_Parity = USART_Parity_No;
	USART_Initstruct.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
	USART_Initstruct.USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
	USART_Init(USART2, &USART_Initstruct);

	USART_Cmd(USART2, ENABLE);

	USART_ITConfig(USART2, USART_IT_RXNE, ENABLE);

	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);

	NVIC_InitStruct.NVIC_IRQChannel = USART2_IRQn;
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 0;
	NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0;
	NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStruct);
}

static buffqueue_t serialQueueRx;
static uint8_t pBuffDataRx[20];
void Serial_Init(void)
{
	bufInit(pBuffDataRx, &serialQueueRx, sizeof(pBuffDataRx[0]), 20);
	USART2_Init();
}

uint8_t PollRxBuff(void)
{
	int a = 0;
	if ((bufNumItems(&serialQueueRx) != 0))
	{
		a++;
	}
}

int main(void)
{
	Serial_Init();
	while(1)
	{
		PollRxBuff();
	}
}












